# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ax < Formula
  desc "Agentic coding DX metrics"
  homepage "https://github.com/acroos/ax"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acroos/ax/releases/download/v0.1.6/ax_0.1.6_darwin_amd64.tar.gz"
      sha256 "5aa9b76af8620cf0ac6d1be2dfb4d841bf64e4f5dca3e3f52df415ed19a6a73f"

      define_method(:install) do
        bin.install "ax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acroos/ax/releases/download/v0.1.6/ax_0.1.6_darwin_arm64.tar.gz"
      sha256 "dda7b6da3d8059b6e72ec38b6310a83a3ba6d2ba14bd634381f433bef414a243"

      define_method(:install) do
        bin.install "ax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acroos/ax/releases/download/v0.1.6/ax_0.1.6_linux_amd64.tar.gz"
      sha256 "d39cff8e3ec9dd2a8bc3dd43d8abced9ce66895601f833190e029b80054bcfae"
      define_method(:install) do
        bin.install "ax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acroos/ax/releases/download/v0.1.6/ax_0.1.6_linux_arm64.tar.gz"
      sha256 "56d58d7a56817fef4ef61a0e81dda71b75d1c0f864be0f5ac96b94a19872169c"
      define_method(:install) do
        bin.install "ax"
      end
    end
  end
end
