# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ax < Formula
  desc "Agentic coding DX metrics"
  homepage "https://github.com/acroos/ax"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/acroos/ax/releases/download/v0.1.7/ax_0.1.7_darwin_amd64.tar.gz"
      sha256 "267947be259e12d22c328f27eb13dc3dde72684ab481a0e80f7f32bdeac08832"

      define_method(:install) do
        bin.install "ax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/acroos/ax/releases/download/v0.1.7/ax_0.1.7_darwin_arm64.tar.gz"
      sha256 "7d99a0917b22735c48302067048c246102e46e74935e2aef593a76a64b3429de"

      define_method(:install) do
        bin.install "ax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/acroos/ax/releases/download/v0.1.7/ax_0.1.7_linux_amd64.tar.gz"
      sha256 "2dd2ddaf149d24b2cd8ac53cbb3e5b916edd40f5c108e70675ac16134ee7bd81"
      define_method(:install) do
        bin.install "ax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acroos/ax/releases/download/v0.1.7/ax_0.1.7_linux_arm64.tar.gz"
      sha256 "8b8cb03e68ddd41f2f5b6adc59bf28332ac57ed40a09c140dc87b07ba7128cf8"
      define_method(:install) do
        bin.install "ax"
      end
    end
  end
end
