# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
      sha256 "17b8c2323d8b3deccc6f35631dc8c2b038ca4bdc09915d5767eee9bc9956de92"
    end
    on_arm do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
      sha256 "83b52dc76e8939805edbe20743b07864268510992c43d55f06a2c0e38f8e2f5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
      sha256 "502d783e784cad94f2dc78d5c67296ca0525c7025deb036b8a4492170ac045cc"
    end
    on_arm do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
      sha256 "608101a17541222e6abeecff13eca839b80d2026d83e42d9e672caa9bb57d694"
    end
  end

  name "ax"
  desc "Agentic coding DX metrics"
  homepage "https://github.com/acroos/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  # No zap stanza required

end
