# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax" do
  version "0.1.3"

  on_macos do
    on_intel do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
      sha256 "710d0c8d8596a2015d58847ff3dba91d7a22f3b478d59b9ccace88c1eb10a80c"
    end
    on_arm do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
      sha256 "d58882b6138bc44ef5a0609015dcba9eb7358bd31d6c84147758710c15d5762f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
      sha256 "d431ad8ff0772b974595bbfa84b167045f250b8dfdbd1dc1b96931175736c3bf"
    end
    on_arm do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
      sha256 "be69219d64ab614a8c0f803fa76d62ab44f74a9ea7b20a63fc37649c10006f6d"
    end
  end

  name "ax"
  desc "Agentic coding DX metrics"
  homepage "https://github.com/acroos/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  # No zap stanza required

end
