# This file was generated by GoReleaser. DO NOT EDIT.
cask "ax" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_darwin_amd64.tar.gz"
      sha256 "d2a7111dc1647788d93c6bb1fb8312bc74b731a7444a12a45eebcf1fe366ea32"
    end
    on_arm do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_darwin_arm64.tar.gz"
      sha256 "263a54a05af438c853f32556b107fbce10087549dae5a8f10c721f9f3f71e8da"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_linux_amd64.tar.gz"
      sha256 "e1aacd108f4808bf2bb4519bbe0e2539285139801c710ed1e92940860593baab"
    end
    on_arm do
      url "https://github.com/acroos/ax/releases/download/v#{version}/ax_#{version}_linux_arm64.tar.gz"
      sha256 "c901fe3252202d02880ae37ce78aafbdfa4e8a1d6ee588b74bd52116b336f14f"
    end
  end

  name "ax"
  desc "Agentic coding DX metrics"
  homepage "https://github.com/acroos/ax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ax"

  # No zap stanza required

end
